version: '3'
services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: streaming-ye
      MYSQL_USER: toto
      MYSQL_PASSWORD: toto
    ports:
      - "3306:3306"
    volumes:
      /var/lib/mysql
volumes:
  : 
