version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: streaming-db
    environment:
      MYSQL_ROOT_PASSWORD: 123
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
    networks:
      - streaming-ye-network

networks:
  streaming-ye-network:

